[package]
name = "procedural_macros"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
quote = "1.0.36"
syn = { version = "1.0", features = ["full"] }
darling = "0.13"


[lib]
proc-macro = true